version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onderwijs
      POSTGRES_USER: onderwijs
      POSTGRES_PASSWORD: insecure

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      ONDERWIJS_OBJECTSTORE_PASSWORD:
      SECRET_KEY: insecure
      DATABASE_NAME: onderwijs
      DATABASE_USER: onderwijs
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "onderwijs.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      UWSGI_STATIC_INDEX: index.html
      # UWSGI_STATIC_MAP: # See /web/deploy/docker-run.sh
    command: >
        bash -c "/deploy/docker-wait.sh \
                && /deploy/docker-migrate.sh \
                && /deploy/docker-run.sh"
