version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onderwijs
      POSTGRES_USER: onderwijs
      POSTGRES_PASSWORD: insecure

  web:
    build: ./web
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      ONDERWIJS_OBJECTSTORE_PASSWORD:
      SECRET_KEY: insecure
      DATABASE_NAME: onderwijs
      DATABASE_USER: onderwijs
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "onderwijs.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
    volumes:  # for development we use bind mounts
      - ./web/app/:/app/
      - ./web/deploy/:/deploy/
      - onderwijs_import_cache:/data/
    # Note we are using manage.py runserver for local dev, because UWSGI does
    # not reload automatically when a file is changed (and we do not want to
    # continually rebuild the docker images).
    command: >
        bash -c "/deploy/docker-wait.sh \
                && /deploy/docker-migrate.sh \
                && python manage.py runserver 0.0.0.0:8000"

volumes:
  onderwijs_import_cache:
