version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onderwijs
      POSTGRES_USER: onderwijs
      POSTGRES_PASSWORD: insecure

  web:
    build: ./web
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      SECRET_KEY: insecure
      DATABASE_NAME: onderwijs
      DATABASE_USER: onderwijs
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "onderwijs.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
    volumes:  # for development we use source mounts
      - ./web/app/:/app/
      - ./web/deploy/:/deploy/
    command: >
        bash -c "/deploy/docker-wait.sh \
                && /deploy/docker-migrate.sh \
                && /deploy/docker-run.sh"
