version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backups:/tmp/backups
    environment:
      POSTGRES_DB: onderwijs
      POSTGRES_USER: onderwijs
      POSTGRES_PASSWORD: insecure

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/onderwijs:${ENVIRONMENT}
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      ONDERWIJS_OBJECTSTORE_PASSWORD:
      SECRET_KEY: insecure
      DATABASE_NAME: onderwijs
      DATABASE_USER: onderwijs
      DATABASE_PASSWORD: insecure
    volumes:
      - gastransitie_import_cache:/data
    command: >
        bash -c "/deploy/docker-wait.sh \
                && /deploy/docker-migrate.sh \
                && python manage.py run_import \
                && python manage.py download_data \
                && python manage.py import_non_public"

volumes:
  gastransitie_import_cache:
